### ISSUE TITLE
Kanban Board

### ISSUE THREAD

**Issue by Juanse7793** [Juanse7793/Final-Capstone-Back-end#7]
Hi dear reviewer

in this group we are 3 people @qwibbler :100: , @tafaramafemba :heavy_check_mark:  and @Juanse7793 :+1:  

here is the [Link](https://github.com/users/Juanse7793/projects/2) to our kanban board

### Repositories

- [Front-end Repo](https://github.com/Juanse7793/Final-Capstone-Front-end)

- [Back-end Repo](https://github.com/Juanse7793/Final-Capstone-Back-end)

### Current state of the kanban board:
![Screenshot from 2022-08-10 11-18-38](https://user-images.githubusercontent.com/96317674/183961621-dc659e79-6ddb-46aa-b2c2-72c9b87842b4.png)

**Comment by vichuge** [comment]
Hi dear student, 

In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![InbornCandidHornet-size_restricted](https://user-images.githubusercontent.com/20563252/121368858-ff93ee80-c900-11eb-9ee8-e43b2b0d3382.gif)

Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
